# Generated by Django 4.1.6 on 2023-02-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0001_initial'),
    ]

    operations = [
    ]
